CREATE TABLE IF NOT EXISTS users (
  id SERIAL NOT NULL PRIMARY KEY,
	github_id INT DEFAULT NULL,
	fortytwo_id INT DEFAULT NULL,
  username VARCHAR(1000) NOT NULL,
  firstname VARCHAR(1000) NOT NULL,
  lastname VARCHAR(1000) NOT NULL,
	email VARCHAR(1000), 
	password VARCHAR(1000) NOT NULL,
	profile_picture VARCHAR(1000) DEFAULT 'dog.png',
	completed BOOLEAN DEFAULT 'f',
	token VARCHAR(1000),
	language VARCHAR(255) DEFAULT 'en'
);

CREATE TABLE IF NOT EXISTS comments (
	id SERIAL NOT NULL PRIMARY KEY,
	user_id INT NOT NULL,
	yts_id VARCHAR(255) NOT NULL,
	content VARCHAR(1000) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS downloads (
	id SERIAL NOT NULL PRIMARY KEY,
	yts_id VARCHAR(15) NOT NULL,
	file_type VARCHAR(10) NOT NULL,
	file_size BIGINT NOT NULL,
	path VARCHAR(255) NOT NULL,
	completed BOOLEAN DEFAULT 'f' 
);

CREATE TABLE IF NOT EXISTS watched_movies (
	id SERIAL NOT NULL PRIMARY KEY,
	yts_id VARCHAR(15) NOT NULL,
	user_id INT NOT NULL,
	last_watched TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS subtitles (
	id SERIAL NOT NULL PRIMARY KEY,
	yts_id VARCHAR(255) NOT NULL,
	language VARCHAR(255) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	path VARCHAR(255) NOT NULL
);
