CREATE TABLE IF NOT EXISTS users (
  id SERIAL NOT NULL PRIMARY KEY,
  username VARCHAR(1000) NOT NULL,
  firstname VARCHAR(1000) NOT NULL,
  lastname VARCHAR(1000) NOT NULL,
	email VARCHAR(1000), 
	password VARCHAR(1000) NOT NULL,
	profile_picture VARCHAR(1000),
	completed BOOLEAN DEFAULT 'f',
	token VARCHAR(1000),
	language VARCHAR(255) DEFAULT 'en',
);

CREATE TABLE IF NOT EXISTS comments (
	id SERIAL NOT NULL PRIMARY KEY,
	user_id INT NOT NULL,
	imdb_id VARCHAR(255) NOT NULL,
	content VARCHAR(1000) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
);

CREATE TABLE IF NOT EXISTS downloads (
	id SERIAL NOT NULL PRIMARY KEY,
	imdb_id VARCHAR(15) NOT NULL,
	file_type VARCHAR(10) NOT NULL,
	file_size BIGINT NOT NULL,
	resolution VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS watched_movies (
	id SERIAL NOT NULL PRIMARY KEY,
	imdb_id VARCHAR(15) NOT NULL,
	user_id INT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS subtitles (
	id SERIAL NOT NULL PRIMARY KEY,
	imdb_id VARCHAR(255) NOT NULL,
	language VARCHAR(255) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
